### ISSUE TITLE
What's the function of "DSK"?

### ISSUE THREAD

**Issue by nxtreaming** [MengLi619/libobs-node#10]
What is the "DSK" component ?

**Comment by MengLi619** [comment]
DSK means "Down Stream Key", It's a function to always show Logo/Character component during the transition.
Current DSK function is only a temprary implementation (For demo purpose). But we already tested OBS can support DSK 
by duplicated scene without any problem.

I hope it can help you, thank you.

**Comment by nxtreaming** [comment]
Thanks, 
I will test this feature once it has done.
